"""
Enumerations et constantes ZFS EXTRAITES AUTOMATIQUEMENT du source.

Source : vendor/zfs-linux-2.3.9 (en-tetes spa.h, zio.h, zio_compress.h,
dmu.h, fs/zfs.h).

NE PAS EDITER A LA MAIN : regenerer avec
    python3 scripts/40_gen_enums.py
"""

OPENZFS_SOURCE = "zfs-linux-2.3.9"

ZIO_COMPRESS = {
    0: "ZIO_COMPRESS_INHERIT",
    1: "ZIO_COMPRESS_ON",
    2: "ZIO_COMPRESS_OFF",
    3: "ZIO_COMPRESS_LZJB",
    4: "ZIO_COMPRESS_EMPTY",
    5: "ZIO_COMPRESS_GZIP_1",
    6: "ZIO_COMPRESS_GZIP_2",
    7: "ZIO_COMPRESS_GZIP_3",
    8: "ZIO_COMPRESS_GZIP_4",
    9: "ZIO_COMPRESS_GZIP_5",
    10: "ZIO_COMPRESS_GZIP_6",
    11: "ZIO_COMPRESS_GZIP_7",
    12: "ZIO_COMPRESS_GZIP_8",
    13: "ZIO_COMPRESS_GZIP_9",
    14: "ZIO_COMPRESS_ZLE",
    15: "ZIO_COMPRESS_LZ4",
    16: "ZIO_COMPRESS_ZSTD",
    17: "ZIO_COMPRESS_FUNCTIONS",
}

ZIO_COMPRESS_NAMES = {
    0: "inherit",
    1: "on",
    2: "off",
    3: "lzjb",
    4: "empty",
    5: "gzip_1",
    6: "gzip_2",
    7: "gzip_3",
    8: "gzip_4",
    9: "gzip_5",
    10: "gzip_6",
    11: "gzip_7",
    12: "gzip_8",
    13: "gzip_9",
    14: "zle",
    15: "lz4",
    16: "zstd",
    17: "functions",
}

ZIO_CHECKSUM = {
    0: "ZIO_CHECKSUM_INHERIT",
    1: "ZIO_CHECKSUM_ON",
    2: "ZIO_CHECKSUM_OFF",
    3: "ZIO_CHECKSUM_LABEL",
    4: "ZIO_CHECKSUM_GANG_HEADER",
    5: "ZIO_CHECKSUM_ZILOG",
    6: "ZIO_CHECKSUM_FLETCHER_2",
    7: "ZIO_CHECKSUM_FLETCHER_4",
    8: "ZIO_CHECKSUM_SHA256",
    9: "ZIO_CHECKSUM_ZILOG2",
    10: "ZIO_CHECKSUM_NOPARITY",
    11: "ZIO_CHECKSUM_SHA512",
    12: "ZIO_CHECKSUM_SKEIN",
    13: "ZIO_CHECKSUM_EDONR",
    14: "ZIO_CHECKSUM_BLAKE3",
    15: "ZIO_CHECKSUM_FUNCTIONS",
}

ZIO_CHECKSUM_NAMES = {
    0: "inherit",
    1: "on",
    2: "off",
    3: "label",
    4: "gang_header",
    5: "zilog",
    6: "fletcher_2",
    7: "fletcher_4",
    8: "sha256",
    9: "zilog2",
    10: "noparity",
    11: "sha512",
    12: "skein",
    13: "edonr",
    14: "blake3",
    15: "functions",
}

DMU_OBJECT_TYPE = {
    0: "DMU_OT_NONE",
    1: "DMU_OT_OBJECT_DIRECTORY",
    2: "DMU_OT_OBJECT_ARRAY",
    3: "DMU_OT_PACKED_NVLIST",
    4: "DMU_OT_PACKED_NVLIST_SIZE",
    5: "DMU_OT_BPOBJ",
    6: "DMU_OT_BPOBJ_HDR",
    7: "DMU_OT_SPACE_MAP_HEADER",
    8: "DMU_OT_SPACE_MAP",
    9: "DMU_OT_INTENT_LOG",
    10: "DMU_OT_DNODE",
    11: "DMU_OT_OBJSET",
    12: "DMU_OT_DSL_DIR",
    13: "DMU_OT_DSL_DIR_CHILD_MAP",
    14: "DMU_OT_DSL_DS_SNAP_MAP",
    15: "DMU_OT_DSL_PROPS",
    16: "DMU_OT_DSL_DATASET",
    17: "DMU_OT_ZNODE",
    18: "DMU_OT_OLDACL",
    19: "DMU_OT_PLAIN_FILE_CONTENTS",
    20: "DMU_OT_DIRECTORY_CONTENTS",
    21: "DMU_OT_MASTER_NODE",
    22: "DMU_OT_UNLINKED_SET",
    23: "DMU_OT_ZVOL",
    24: "DMU_OT_ZVOL_PROP",
    25: "DMU_OT_PLAIN_OTHER",
    26: "DMU_OT_UINT64_OTHER",
    27: "DMU_OT_ZAP_OTHER",
    28: "DMU_OT_ERROR_LOG",
    29: "DMU_OT_SPA_HISTORY",
    30: "DMU_OT_SPA_HISTORY_OFFSETS",
    31: "DMU_OT_POOL_PROPS",
    32: "DMU_OT_DSL_PERMS",
    33: "DMU_OT_ACL",
    34: "DMU_OT_SYSACL",
    35: "DMU_OT_FUID",
    36: "DMU_OT_FUID_SIZE",
    37: "DMU_OT_NEXT_CLONES",
    38: "DMU_OT_SCAN_QUEUE",
    39: "DMU_OT_USERGROUP_USED",
    40: "DMU_OT_USERGROUP_QUOTA",
    41: "DMU_OT_USERREFS",
    42: "DMU_OT_DDT_ZAP",
    43: "DMU_OT_DDT_STATS",
    44: "DMU_OT_SA",
    45: "DMU_OT_SA_MASTER_NODE",
    46: "DMU_OT_SA_ATTR_REGISTRATION",
    47: "DMU_OT_SA_ATTR_LAYOUTS",
    48: "DMU_OT_SCAN_XLATE",
    49: "DMU_OT_DEDUP",
    50: "DMU_OT_DEADLIST",
    51: "DMU_OT_DEADLIST_HDR",
    52: "DMU_OT_DSL_CLONES",
    53: "DMU_OT_BPOBJ_SUBOBJ",
    54: "DMU_OT_NUMTYPES",
}

DMU_OBJECT_TYPE_NAMES = {
    0: "none",
    1: "object_directory",
    2: "object_array",
    3: "packed_nvlist",
    4: "packed_nvlist_size",
    5: "bpobj",
    6: "bpobj_hdr",
    7: "space_map_header",
    8: "space_map",
    9: "intent_log",
    10: "dnode",
    11: "objset",
    12: "dsl_dir",
    13: "dsl_dir_child_map",
    14: "dsl_ds_snap_map",
    15: "dsl_props",
    16: "dsl_dataset",
    17: "znode",
    18: "oldacl",
    19: "plain_file_contents",
    20: "directory_contents",
    21: "master_node",
    22: "unlinked_set",
    23: "zvol",
    24: "zvol_prop",
    25: "plain_other",
    26: "uint64_other",
    27: "zap_other",
    28: "error_log",
    29: "spa_history",
    30: "spa_history_offsets",
    31: "pool_props",
    32: "dsl_perms",
    33: "acl",
    34: "sysacl",
    35: "fuid",
    36: "fuid_size",
    37: "next_clones",
    38: "scan_queue",
    39: "usergroup_used",
    40: "usergroup_quota",
    41: "userrefs",
    42: "ddt_zap",
    43: "ddt_stats",
    44: "sa",
    45: "sa_master_node",
    46: "sa_attr_registration",
    47: "sa_attr_layouts",
    48: "scan_xlate",
    49: "dedup",
    50: "deadlist",
    51: "deadlist_hdr",
    52: "dsl_clones",
    53: "bpobj_subobj",
    54: "numtypes",
}

DMU_OT_BYTESWAP_MASK = 31
DMU_OT_ENCRYPTED = 32
DMU_OT_METADATA = 64
DMU_OT_NEWTYPE = 128
SPA_ASIZEBITS = 24
SPA_BLKPTRSHIFT = 7
SPA_COMPRESSBITS = 7
SPA_DVAS_PER_BP = 3
SPA_LSIZEBITS = 16
SPA_MINBLOCKSHIFT = 9
SPA_PSIZEBITS = 16
SPA_VDEVBITS = 24
